global:
  scrape_interval: 5s

scrape_configs:
- job_name: 'deviceservice'
  metrics_path: /metrics
  static_configs:
  - targets: [ 'deviceservice.api:8080' ]

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertManager:9093"

rule_files:
- "/etc/prometheus/rules/*.yml"
