global:
  scrape_interval: "5s"

scrape_configs:
  - job_name: "deviceservice"
    metrics_path: "/metrics"
    static_configs: 
      - targets: ["deviceservice.api:8080"]

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']