name: CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  publish-image:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest

    steps:
    # -----------------------------------
    # Checkout the repository
    # ----------------------------------- 
    - name: Checkout repository
      uses: actions/checkout@v4

    # ------------------------------------
    # Log in to GitHub Container Registry
    # ------------------------------------
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    # -----------------------------------
    # Build Docker Image
    # -----------------------------------
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/smarthome-deviceservice:latest \
                       -t ghcr.io/${{ secrets.GHCR_USERNAME }}/smarthome-deviceservice:${{ github.sha }} \
                       -f EnergyDataService.Api/Dockerfile .

    # -----------------------------------
    # Push Image
    # -----------------------------------
    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/smarthome-deviceservice:latest
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/smarthome-deviceservice:${{ github.sha }}
