name: CI Pipeline

on:
  push:
    branches: [ main, dev, feature/* ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    # -----------------------------
    # Checkout repository
    # -----------------------------
    - name: Checkout repository
      uses: actions/checkout@v4

    # -----------------------------
    # Cache NuGet packages
    # -----------------------------
    - name: Cache NuGet
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj' )}}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # -----------------------------
    # Install .NET SDK 8
    # -----------------------------
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # -----------------------------
    # Restore dependencies
    # -----------------------------

    - name: Restore
      run: dotnet restore SmartHome.sln

    # -----------------------------
    # Build
    # -----------------------------
    - name: Build
      run: dotnet build SmartHome.sln --configuration Release --no-restore

    # -----------------------------
    # Run Unit Tests + Coverage
    # -----------------------------
    - name: Run Tests with Coverage
      run: |
        dotnet test EnergyDataService.Tests/EnergyDataService.Tests.csproj \
          --configuration Release \
          --no-build \
          --collect:"XPlat Code Coverage" \
          --results-directory TestResults

    # -----------------------------
    # Upload coverage report
    # -----------------------------
    - name: Upload Coverage Results
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: TestResults

    # -----------------------------
    # Upload TRX test results
    # -----------------------------
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: "**/TestResults/*.trx"

    # -----------------------------
    # Validate Dockerfile builds
    # -----------------------------
    - name: Validate Docker build
      run: docker build . -f EnergyDataService.Api/Dockerfile
